const events = {
  ADD_PUBLIC_ROUTE: 'ADD_PUBLIC_ROUTE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SELECT_MODULE: 'SELECT_MODULE',
  CHANGE_SERVICE_POINT: 'CHANGE_SERVICE_POINT',
  ERROR: 'ERROR',
};

export default events;
